---
title: "Homework 5"
author: "Ravi Patel"
date: "April 11, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Part 1
```{r}
if (file.exists("alcohol.rds")) {
  data <- readRDS("alcohol.rds")
} else {
  url <- "https://xdaiisu.github.io/ds202materials/data/ames.csv"
  data <- readr::read_csv(url)
  saveRDS(data, file="alcohol.rds")
} 
```

Part 2 Data Cleaning
```{r}
library(tidyr)
library(lubridate)

# Extract longitude and latitude from Store Location
data <- extract(data, `Store Location`, c("Latitude", "Longitude"), "\\(([^,]+),([^)]+)\\)")

# Change type for certain columns
data$`Vendor Number` = as.numeric(data$`Vendor Number`)
data$Latitude = as.numeric(data$Latitude)
data$Longitude = as.numeric(data$Longitude)
data$Date = mdy(data$Date)

```

Part 3 First Overview
```{r}
library(ggplot2)
library(dplyr)

# Plot store locations
ggplot(data, aes(x=Longitude, y=Latitude)) + geom_point()

# Gallons sold per category
d1 <- data %>%
  group_by(`Category Name`) %>%
  summarise(
    volume = sum(`Volume Sold (Gallons)`)
  )
drop_na(d1)

ggplot(d1, aes(x=`Category Name`, y=volume)) + 
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

